version: '3.5'
services:
  client:
    image: registry.chas.school/cobalt-client-dev:latest
    networks:
      - traefik
    deploy:
      labels:
        traefik.port: '80'
        traefik.backend: 'cobalt_client_dev'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:cobalt-dev.chas.school'
    env_file:
      - .env

networks:
  traefik:
    external: true