export const REQUEST_USER_START = "REQUEST_USER_START";
export const REQUEST_USER_SUCCESS = "REQUEST_USER_SUCCESS";
export const REQUEST_USER_FAIL = "REQUEST_USER_FAIL";

export const REQUEST_AVATAR_UPDATE_START = "REQUEST_AVATAR_UPDATE_START";
export const REQUEST_AVATAR_UPDATE_SUCCESS = "REQUEST_AVATAR_UPDATE_SUCCESS";
export const REQUEST_AVATAR_UPDATE_FAIL = "REQUEST_AVATAR_UPDATE_FAIL";
