export const ADD_MEMBER_START = "ADD_MEMBER_START";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_ERROR = "ADD_MEMBER_ERROR";
export const REMOVE_MEMBER_START = "REMOVE_MEMBER_START";
export const REMOVE_MEMBER_SUCCESS = "REMOVE_MEMBER_SUCCESS";
export const REMOVE_MEMBER_ERROR = "REMOVE_MEMBER_ERROR";
